<?php
// $Id$

function spectacles_views_analyze($view) {
  $ret = array();

  $view->execute_display('default');

  $results = db_query('EXPLAIN '. $view->build_info['query'], $view->build_info['query_args']);

  while ($row = db_fetch_array($results)) {
    if (strstr($row['Extra'], 'filesort')) {
      $ret[] = views_ui_analysis(t('Your view results in a filesort. Be careful: kittens may die.'), 'warning');
    }
  }

  return $ret;
}
